// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612101812_UpdateRequestToPayRefundRelation")]
    partial class UpdateRequestToPayRefundRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BankSystem.Models.BasicUserInfoResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Birthdate")
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GivenName")
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BasicUserInfomation");
                });

            modelBuilder.Entity("BankSystem.Models.CreatePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerReference")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceProviderUserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CreatePayments");
                });

            modelBuilder.Entity("BankSystem.Models.Deposit", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepositId"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PayeeNote")
                        .HasColumnType("longtext");

                    b.Property<string>("PayerMessage")
                        .HasColumnType("longtext");

                    b.HasKey("DepositId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("BankSystem.Models.GetAccountBalance", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("AvailableBalance")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("BankSystem.Models.GetAccountBalanceInSpecificCurrency", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AccountBalancesInSpecificCurrency");
                });

            modelBuilder.Entity("BankSystem.Models.GetBasicUserInfo", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Birthdate")
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GivenName")
                        .HasColumnType("longtext");

                    b.Property<string>("Locale")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BasicUserInfos");
                });

            modelBuilder.Entity("BankSystem.Models.Refund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("PayeeNote")
                        .HasColumnType("longtext");

                    b.Property<string>("PayerMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("ReferenceIdToRefund")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceIdToRefund");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("BankSystem.Models.RequestToPay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("PayeeNote")
                        .HasColumnType("longtext");

                    b.Property<string>("PayerMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RequestToPays");
                });

            modelBuilder.Entity("CreateInvoiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValidityDuration")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GetPaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatePaymentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatePaymentId")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("BankSystem.Models.CreatePayment", b =>
                {
                    b.OwnsOne("BankSystem.Models.Money", "Money", b1 =>
                        {
                            b1.Property<int>("CreatePaymentId")
                                .HasColumnType("int");

                            b1.Property<string>("Amount")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CreatePaymentId");

                            b1.ToTable("CreatePayments");

                            b1.WithOwner()
                                .HasForeignKey("CreatePaymentId");
                        });

                    b.Navigation("Money");
                });

            modelBuilder.Entity("BankSystem.Models.Deposit", b =>
                {
                    b.OwnsOne("BankSystem.Models.Party", "Payee", b1 =>
                        {
                            b1.Property<int>("DepositId")
                                .HasColumnType("int");

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PartyIdType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("DepositId");

                            b1.ToTable("Deposits");

                            b1.WithOwner()
                                .HasForeignKey("DepositId");
                        });

                    b.Navigation("Payee")
                        .IsRequired();
                });

            modelBuilder.Entity("BankSystem.Models.Refund", b =>
                {
                    b.HasOne("BankSystem.Models.RequestToPay", "RequestToPay")
                        .WithMany("Refunds")
                        .HasForeignKey("ReferenceIdToRefund")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestToPay");
                });

            modelBuilder.Entity("BankSystem.Models.RequestToPay", b =>
                {
                    b.OwnsOne("BankSystem.Models.Payer", "Payer", b1 =>
                        {
                            b1.Property<int>("RequestToPayId")
                                .HasColumnType("int");

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PartyIdType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("RequestToPayId");

                            b1.ToTable("RequestToPays");

                            b1.WithOwner()
                                .HasForeignKey("RequestToPayId");
                        });

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("CreateInvoiceModel", b =>
                {
                    b.OwnsOne("Party", "IntendedPayer", b1 =>
                        {
                            b1.Property<int>("CreateInvoiceModelId")
                                .HasColumnType("int");

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PartyIdType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CreateInvoiceModelId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("CreateInvoiceModelId");
                        });

                    b.OwnsOne("Party", "Payee", b1 =>
                        {
                            b1.Property<int>("CreateInvoiceModelId")
                                .HasColumnType("int");

                            b1.Property<string>("PartyId")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PartyIdType")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CreateInvoiceModelId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("CreateInvoiceModelId");
                        });

                    b.Navigation("IntendedPayer");

                    b.Navigation("Payee");
                });

            modelBuilder.Entity("GetPaymentStatus", b =>
                {
                    b.HasOne("BankSystem.Models.CreatePayment", "CreatePayment")
                        .WithOne("PaymentStatus")
                        .HasForeignKey("GetPaymentStatus", "CreatePaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatePayment");
                });

            modelBuilder.Entity("BankSystem.Models.CreatePayment", b =>
                {
                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("BankSystem.Models.RequestToPay", b =>
                {
                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
